name: evobind
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.12.0
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - biopython==1.81
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - chex==0.1.86
      - contextlib2==21.6.0
      - dm-haiku==0.0.12
      - dm-tree==0.1.8
      - etils==1.9.2
      - flatbuffers==24.3.25
      - flax==0.8.5
      - fsspec==2024.6.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h5py==3.11.0
      - idna==3.7
      - immutabledict==4.2.0
      - importlib-resources==6.4.0
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jaxlib==0.4.30
      - jmp==0.0.4
      - keras==3.4.1
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.3.2
      - msgpack==1.0.8
      - namex==0.0.8
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.5.3.2
      - nvidia-cuda-cupti-cu12==12.5.82
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-runtime-cu12==12.5.82
      - nvidia-cudnn-cu12==9.1.1.17
      - nvidia-cufft-cu12==11.2.3.61
      - nvidia-cusolver-cu12==11.6.3.83
      - nvidia-cusparse-cu12==12.5.1.3
      - nvidia-nccl-cu12==2.22.3
      - nvidia-nvjitlink-cu12==12.5.82
      - opt-einsum==3.3.0
      - optax==0.2.2
      - optree==0.11.0
      - orbax-checkpoint==0.5.20
      - packaging==24.1
      - pandas==2.2.2
      - protobuf==4.25.3
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - rich==13.7.1
      - scipy==1.14.0
      - six==1.16.0
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorstore==0.1.63
      - termcolor==2.4.0
      - toolz==0.12.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - zipp==3.19.2
